---
date: '2015-07-15'
---
# 目录
- [一、关于本站](#aboutSite)
- [二、关于XRLAB](#aboutLab)
- [三、联系我们](#contactUs)
- [四、地理位置](#xrlabGeo)


# 一、<span id="aboutSite">关于本站</span>
    
本站是XRLAB团队综合信息分享交流网站。秉持*学术导向，内容为王；知识丰富，形式从简*和**综合研究文化建设**的办站理念。内容主要由研究生、创新班、社团学生、项目组提供素材，作为日常任务共同维护，每周不定时更新，投稿邮箱：860080618@qq.com。

    注：所有指导社团的相关信息发布、公示、展示和活动均在此网站进行，不再单独建立网站和微信公众号等，主要精力向学术研究靠近。
    
如果你有好的建议和意见：请填写XRLAB网站意见收集及反馈表https://docs.qq.com/doc/DT2VDVkZ3VkFCd3Fo

## 技术框架
技术建站同时，灵活多样的使用其他各种提升效率的技术如：云盘、共享文档等；各类专业托管网站如：Researchgate，Mendeley等。

### 主要技术
- [Github](https://github.com/):托管网站
- [Git](https://git-scm.com/)：推送更新
- [Markdown](https://markdown.com.cn/)：基本的内容编写语言
- [Hugo](https://www.gohugo.org/): 网站模板
- [R](https://cran.r-project.org/)：全面支持R+markdown的高级内容编写
- [Rstudio](https://rstudio.com/)：方便编写内容的编辑器
- [Rmarkdown](https://rmarkdown.rstudio.com/)：结合R和markdown的强大动力
- [Netlify](https://www.netlify.com/)：自动发布和发布备用

### 域名管理

+ 主用域名：[www.xrlab.org](https://xrlab.org/) 
+ 备用域名：[xrlab.netlify.app](https://xrlab.netlify.app/)

### 更新管理

- 第1步：研究生、创新班成员、社团、项目组下载或自建网站模板
- 第2步：根据模板用Markdown、Rmarkdown或HTML格式撰写内容
- 第3步：内容【标签】主要包括
  + 周报：一周的进展简短交流汇报,通过共享文档随时写成，周末更新至网站
  + 月报：月报为学术导向，主要介绍最新论文和领域的发展
  + 获奖：科技获奖、学生竞赛获奖等
  + 专著：出版完成的专著的介绍
  + 论文：发表的论文信的介绍
  + 专利：授权的专利的介绍
  + 软著：获批软著的介绍
  + 演示：制作的PPT等相关演示
  + 软件：常用软件的讲解
  + 硬件：常用硬件的讲解
  + 科普：社团的科普知识
  + 项目：项目信息和管理介绍
  + 活动：学生的组织的活动等
  + 团队：研究团伙、合作伙伴等
  + 社团：各社团活动用单独子标签【SIT】【ERA】【iDRREM】
  + 例会：XRLAB的周会、月会和年会等
  + 其他
- 老师审查后修改后上传并发布
- 定期发布内容和更新

# 二、 <span id="aboutLab">综合减灾研究室</span>


## 1. 研究室介绍
[研究室介绍]([XRLAB](https://www.xrlab.org/2015/07/15/xrlab/))

## 2. 团队介绍
### 负责人
[田兵伟 副教授](https://www.xrlab.org/tian/)

### 科研人员

### 主要合作者

### 研究生

### 创新班

### 学生社团
四川大学学术型学生社团

1. [四川大学空间信息技术学会](https://www.xrlab.org/2015/10/13/scusit/)

2. [四川大学应急救援学会](https://www.xrlab.org/2016/11/09/scuera/)

3. [四川大学国际减灾与应急管理学会](https://www.xrlab.org/2019/10/13/idrrem/)


### 项目组
## 3. 项目合作

[DREAM地图项目](https://www.xrlab.org/2016/09/29/dream/)
[VR安全项目]()
[应急课程开发项目]()


# 三、<span id="contactUs">联系我们</span>
- 校区：四川大学江安校区（东校区）
- 地址：四川省成都市双流区黄河中路一段122号 香港马会大楼
- 单位：四川大学-香港理工大学 灾后重建与管理学院 ([IDMR](http://idmr.scu.edu.cn/))
- 邮编：610207
- 邮件：xrlab@foxmail.com

# 四、<span id="xrlabGeo">地理位置</span>

```{r}
library(leaflet)
map <- leaflet()
at <- addTiles(map)
addMarkers(at,lng=104.0067, lat=30.56346, popup="这里是XRLAB")
```

*最后更新于`r Sys.time()`* 本页源代码请[点击下载]()
