---
date: "2015-07-15"
title: 【初心】为什么叫XRLAB？
slug: xrlab
categories: []
tags: []
---

XRLAB中的X代表未知和创新，XR主要指X个R打头的研兴趣和方向，分别指研究，即研究以Resilience为中心的综合减灾；研究以RS为中心的3S减灾技术；研究以RS为中心的3S减灾技术；研究以RS为中心的3S减灾技术；研究以R为中心的灾害大数据技术。LAB是Labratory的缩略，指研究室，固XRLAB简称综合减灾研究室。

## 研究以Resilience为核心的综合减灾
   - Risk Assessment & Avoidance/Prevention  防灾：事前防灾免灾避灾
   - Risk Reduction/Disaster Mitigation/     减灾：事前减灾发展
   - Readiness/Preparation/Risk transfer     备灾：事前备灾应急准备
   - Response/Rescue/Relief  救灾：事中应变应急响应救援救急
   - Recovery  事后恢复善后
   - Reconstruction 灾后重建规划
   - Rehablitation  灾后康复
   - Return/Risk retention 恢复到原状
   - Risk Communication 风险沟通
   - *Resilience 韧性：一心强韧，综合减灾*

## 研究以RS为核心的3S减灾技术
   - RS    遥感
   - GIS   地理信息系统
      - 讲授硕士课程《3S减灾技术及其应用》
   - GNSS  导航定位系统
   - UAV   无人机技术
      - 讲授本科课程《无人飞行器在防灾减灾中的应用》
   - Map   参与式制图方法
      - [DREAM地图](http://tdream.org),
      - 主编《减灾生态艺术地图创新与实践》. 四川美术出版社. 2016

## 研究以VR为核心的虚拟仿真技术
   - VR   虚拟现实
   - AR   扩展现实
   - MR   混合现实
   - BIM  建筑信息模型
   - Digital twin  数字孪生

## 研究以R为核心的灾害大数据技术
   - R Diaster   灾害大数据：讲授课程《灾害信息学与大数据》
   - R Visualization 可视化
   - R GeoHealth 健康地理大数据
